"""Tests for extended lockfile parsers (Poetry, pnpm, Yarn, Cargo.toml)."""

import pytest
from pathlib import Path
from taintrace.lockfile import LockfileParser


class TestPoetryLockParser:
    """Parse Poetry lockfiles (poetry.lock)."""

    def test_parse_basic_poetry_lock(self, tmp_path):
        """Extracts package names and versions from poetry.lock."""
        poetry_lock = tmp_path / "poetry.lock"
        poetry_lock.write_text("""# This file is automatically @generated by Poetry 1.8.0.
[[package]]
name = "requests"
version = "2.31.0"

[[package]]
name = "typosquat-req"
version = "1.0.0"
""")
        parser = LockfileParser()
        deps = parser.parse(poetry_lock)
        names = [d.name for d in deps]
        assert "requests" in names
        assert "typosquat-req" in names
        assert all(d.ecosystem == "python" for d in deps)

    def test_parse_empty_poetry_lock(self, tmp_path):
        """Handles empty poetry.lock gracefully."""
        poetry_lock = tmp_path / "poetry.lock"
        poetry_lock.write_text("# Empty lockfile\n")
        parser = LockfileParser()
        deps = parser.parse(poetry_lock)
        assert len(deps) == 0


class TestPnpmLockParser:
    """Parse pnpm lockfiles (pnpm-lock.yaml)."""

    def test_parse_pnpm_v9_lock(self, tmp_path):
        """Parses pnpm v9+ lockfile format with packages: section."""
        pnpm_lock = tmp_path / "pnpm-lock.yaml"
        pnpm_lock.write_text("""lockfileVersion: '9.0'

packages:
  /react/18.2.0:
    resolution: {}
  /lodash/4.17.21:
    resolution: {}
  /@types/react/18.2.0:
    resolution: {}
""")
        parser = LockfileParser()
        deps = parser.parse(pnpm_lock)
        names = [d.name for d in deps]
        assert "react" in names
        assert "lodash" in names
        assert "@types/react" in names
        assert all(d.ecosystem == "node" for d in deps)

    def test_parse_pnpm_v6_lock(self, tmp_path):
        """Parses older pnpm lockfile format with dependencies: section."""
        pnpm_lock = tmp_path / "pnpm-lock.yaml"
        pnpm_lock.write_text("""lockfileVersion: '6.0'

dependencies:
  react: 18.2.0
  lodash: 4.17.21
""")
        parser = LockfileParser()
        deps = parser.parse(pnpm_lock)
        names = [d.name for d in deps]
        assert "react: 18.2.0" in names or "react" in names


class TestYarnLockParser:
    """Parse Yarn Classic lockfiles (yarn.lock)."""

    def test_parse_basic_yarn_lock(self, tmp_path):
        """Parses Yarn Classic lockfile format."""
        yarn_lock = tmp_path / "yarn.lock"
        yarn_lock.write_text("""# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

react@^18.2.0:
  version "18.2.0"
  integrity sha512-...

lodash@^4.17.21:
  version "4.17.21"
  integrity sha512-...

@types/react@^18.2.0:
  version "18.2.0"
  integrity sha512-...
""")
        parser = LockfileParser()
        deps = parser.parse(yarn_lock)
        names = [d.name for d in deps]
        assert "react" in names
        assert "lodash" in names
        assert "@types/react" in names
        assert all(d.ecosystem == "node" for d in deps)

    def test_skip_workspace_packages(self, tmp_path):
        """Skips workspace packages (local)."""
        yarn_lock = tmp_path / "yarn.lock"
        yarn_lock.write_text("""# yarn lockfile v1

my-local-pkg@workspace:.
  version "1.0.0"

react@^18.2.0:
  version "18.2.0"
""")
        parser = LockfileParser()
        deps = parser.parse(yarn_lock)
        names = [d.name for d in deps]
        assert "my-local-pkg" not in names
        assert "react" in names

    def test_parse_empty_yarn_lock(self, tmp_path):
        """Handles empty yarn.lock gracefully."""
        yarn_lock = tmp_path / "yarn.lock"
        yarn_lock.write_text("# Empty\n")
        parser = LockfileParser()
        deps = parser.parse(yarn_lock)
        assert len(deps) == 0


class TestCargoTomlParser:
    """Parse Cargo.toml for dependency names."""

    def test_parse_basic_cargo_toml(self, tmp_path):
        """Extracts dependencies from Cargo.toml."""
        cargo_toml = tmp_path / "Cargo.toml"
        cargo_toml.write_text("""[package]
name = "my-app"
version = "0.1.0"

[dependencies]
serde = "1.0"
tokio = { version = "1.0", features = ["full"] }
""")
        parser = LockfileParser()
        deps = parser.parse(cargo_toml)
        names = [d.name for d in deps]
        assert "serde" in names
        assert "tokio" in names
        assert all(d.ecosystem == "rust" for d in deps)

    def test_parse_dev_dependencies(self, tmp_path):
        """Extracts dev-dependencies too."""
        cargo_toml = tmp_path / "Cargo.toml"
        cargo_toml.write_text("""[dependencies]
serde = "1.0"

[dev-dependencies]
tokio-test = "0.4"
""")
        parser = LockfileParser()
        deps = parser.parse(cargo_toml)
        names = [d.name for d in deps]
        assert "tokio-test" in names
