"""Tests for uv.lock parser support."""
from __future__ import annotations
from pathlib import Path
from taintrace.lockfile import LockfileParser


class TestUvLockParser:
    def test_uv_lock_basic(self, tmp_path):
        content = """# This file is autogenerated by uv via the following command:
#    uv pip compile pyproject.toml -o uv.lock
version = 0
requires-python = ">=3.10"

[[package]]
name = "requests"
version = "2.31.0"

[[package]]
name = "flask"
version = "3.0.0"
"""
        p = tmp_path / "uv.lock"
        p.write_text(content)
        parser = LockfileParser()
        deps = parser.parse(p)
        names = [d.name for d in deps]
        assert "requests" in names
        assert "flask" in names
        assert all(d.ecosystem == "python" for d in deps)

    def test_uv_lock_empty(self, tmp_path):
        p = tmp_path / "uv.lock"
        p.write_text("")
        parser = LockfileParser()
        deps = parser.parse(p)
        assert deps == []

    def test_uv_lock_complex(self, tmp_path):
        content = """[[package]]
name = "django"
version = "4.2.0"

[[package]]
name = "celery"
version = "5.3.0"
"""
        p = tmp_path / "uv.lock"
        p.write_text(content)
        parser = LockfileParser()
        deps = parser.parse(p)
        assert len(deps) == 2
